#!/bin/sh

module="scull"
device="scull"
mode="664"

load_scull_driver() {
    set -e

    if grep -q '^staff:' /etc/group; then
        group="staff"
    else
        group="wheel"
    fi

    insmod /lib/modules/$(uname -r)/extra/${module}.ko $* || exit 1
    echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
    if [ ! -z ${major} ]; then
        rm -f /dev/${device}[0-3]
        mknod /dev/${device}0 c $major 0
        mknod /dev/${device}1 c $major 1
        mknod /dev/${device}2 c $major 2
        mknod /dev/${device}3 c $major 3
        ln -sf ${device}0 /dev/${device}
        chgrp $group /dev/${device}[0-3]
        chmod $mode /dev/${device}[0-3]

        rm -f /dev/${device}pipe[0-3]
        mknod /dev/${device}pipe0 c $major 4
        mknod /dev/${device}pipe1 c $major 5
        mknod /dev/${device}pipe2 c $major 6
        mknod /dev/${device}pipe3 c $major 7
        ln -sf ${device}pipe0 /dev/${device}pipe
        chgrp $group /dev/${device}pipe[0-3]
        chmod $mode /dev/${device}pipe[0-3]

        rm -f /dev/${device}single
        mknod /dev/${device}single c $major 8
        chgrp $group /dev/${device}single
        chmod $mode /dev/${device}single

        rm -f /dev/${device}uid
        mknod /dev/${device}uid c $major 9
        chgrp $group /dev/${device}uid
        chmod $mode /dev/${device}uid

        rm -f /dev/${device}wuid
        mknod /dev/${device}wuid c $major 10
        chgrp $group /dev/${device}wuid
        chmod $mode /dev/${device}wuid

        rm -f /dev/${device}priv
        mknod /dev/${device}priv c $major 11
        chgrp $group /dev/${device}priv
        chmod $mode /dev/${device}priv
    else
        echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
    fi
}

unload_scull_driver() {
    # invoke rmmod with all arguments we got
    rmmod $module || exit 1

    # Remove stale nodes

    rm -f /dev/${device} /dev/${device}[0-3]
    rm -f /dev/${device}priv
    rm -f /dev/${device}pipe /dev/${device}pipe[0-3]
    rm -f /dev/${device}single
    rm -f /dev/${device}uid
    rm -f /dev/${device}wuid
}

case "$1" in
start)
    echo "Starting scull driver"
    load_scull_driver
    ;;
stop)
    echo "Stopping scull driver"
    unload_scull_driver
    ;;
*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
